name: store_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_offline: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  very_good_analysis: ^5.1.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

 

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - assets/images/
  fonts:
    #Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400 
    # English Font 
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400 
